title: Sheikh Araf
baseurl: ""

date_format: "%d-%m-%Y"

google_analytics: UA-66412815-1
disqus_shortname:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    none

