title: Sheikh Araf
baseurl: "//sheikharaf.com"
url: "https://sheikharaf.com"

date_format: "%d-%m-%Y"

google_analytics: G-ZCV0L117TE
disqus_shortname:

# Site variables
author_name: "Sheikh Araf"
author_email: "arafsheikh@gmail.com"

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    none
future: true

# Feed
feed:
  path: feed.xml

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-redirect-from
