title: Sheikh Araf
baseurl: "http://sheikharaf.me"

date_format: "%d-%m-%Y"

google_analytics: UA-66412815-1
disqus_shortname:

# Site variables
author_name: "Sheikh Araf"
author_email: "arafsheikh@gmail.com"

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    none
future: true

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
